# Default values for pb-blueprint-ruby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 843222783279.dkr.ecr.us-east-1.amazonaws.com/productboard/pb-service-images
  tag: pb-rfc-notifier
  # pullPolicy: IfNotPresent
  # force reload the image all the time
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  annotations:
    # Reference: https://docs.traefik.io/v1.7/user-guide/kubernetes/#specifying-routing-priorities
    kubernetes.io/ingress.class: traefik-info
    traefik.ingress.kubernetes.io/priority: "1"
  hosts:
    - host: "pb-rfc-notifier.productboard.info"
      # internal cluster traffic runs without TLS
      port: 80
      paths: ["/"]

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

extraEnv: {}
