# Default values for pb-blueprint-ruby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 843222783279.dkr.ecr.us-east-1.amazonaws.com/productboard/pb-rfc-notifier
  tag: pb-rfc-notifier
  # pullPolicy: IfNotPresent
  # force reload the image all the time
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

podAnnotations: { ad.datadoghq.com/tags: '{"team": "fep"}' }

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik-net-internal
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/hsts-include-subdomains: "true"
    ingress.kubernetes.io/hsts-max-age: "315360000"
    ingress.kubernetes.io/hsts-preload: "true"
  hosts:
    - host: 'pb-rfc-notifier.ranger.ops.productboard.net'
      port: 80
      paths: ['/']

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

extraEnv: {}
