build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.24.0
    entrypoint: ['']
  script:
    - echo "CI_BUILDS_DIR = $CI_BUILDS_DIR"
    - echo "{\"credHelpers\":{\"843222783279.dkr.ecr.us-east-1.amazonaws.com\":\"ecr-login\"}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --cache=true
      --cache-repo=$APP_REPOSITORY_URL
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $APP_IMAGE_URL
      --destination $APP_IMAGE_URL-$CI_COMMIT_SHA
